# Generated by Django 3.2.13 on 2022-12-16 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20221216_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='main.customuser', verbose_name='Автор'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_by',
            field=models.ForeignKey(blank=True, default='nobody', on_delete=django.db.models.deletion.CASCADE, related_name='answer_by', to=settings.AUTH_USER_MODEL, verbose_name='Кому вы хотите написать ответ?'),
        ),
    ]
