# Generated by Django 3.2.13 on 2023-01-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20221216_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_by',
            field=models.IntegerField(blank=True, null=True, verbose_name='на какой комментарий вы хотите ответить?'),
        ),
    ]
