# Generated by Django 3.2.13 on 2023-01-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(null='photos/user.png', upload_to='photos', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='', max_length=40, verbose_name='Имя пользователя'),
        ),
    ]
