# Generated by Django 3.2.13 on 2023-01-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20230104_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='information',
            field=models.CharField(blank=True, max_length=200, verbose_name='Информация о пользователе'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(upload_to='photos', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='description',
            field=models.CharField(blank=True, max_length=120, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Текст вашего комментария'),
        ),
    ]
