# Generated by Django 3.2.13 on 2023-02-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20230128_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='information',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Информация о пользователе'),
        ),
    ]
